version: "3.9"
services:
  core-api-1:
    container_name: core-api-1
    image: openjdk:17-oracle
    volumes:
      - ./core-api/build/libs/core-api-0.0.1-SNAPSHOT.jar:/core-api.jar
    command: [ "java", "-jar", "core-api.jar" ]
    environment:
      USER_PROFILE_HOST: "balancer"
      KEYCLOAK_HOST: "keycloak"
      KEYCLOAK_PORT: 8080
      KAFKA_HOST: "kafka"
    networks:
      - skufbet

  core-api-2:
    container_name: core-api-2
    image: openjdk:17-oracle
    volumes:
      - ./core-api/build/libs/core-api-0.0.1-SNAPSHOT.jar:/core-api.jar
    command: [ "java", "-jar", "core-api.jar" ]
    environment:
      USER_PROFILE_HOST: "balancer"
      KEYCLOAK_HOST: "keycloak"
      KEYCLOAK_PORT: 8080
      KAFKA_HOST: "kafka"
    networks:
      - skufbet

  balancer:
    container_name: balancer
    image: nginx
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - "80:80"
    depends_on:
      - core-api-1
      - core-api-2
      - balance-1
      - balance-2
      - user-profile-1
      - user-profile-2
    networks:
      - skufbet

  user-profile-1:
    container_name: user-profile-1
    image: openjdk:17-oracle
    volumes:
      - ./user-profile/build/libs/user-profile-0.0.1-SNAPSHOT.jar:/user-profile.jar
    command: [ "java", "-jar", "user-profile.jar" ]
    environment:
      KAFKA_HOST: "kafka"
    networks:
      - skufbet

  user-profile-2:
    container_name: user-profile-2
    image: openjdk:17-oracle
    volumes:
      - ./user-profile/build/libs/user-profile-0.0.1-SNAPSHOT.jar:/user-profile.jar
    command: [ "java", "-jar", "user-profile.jar" ]
    environment:
      KAFKA_HOST: "kafka"
    networks:
      - skufbet

  balance-1:
    container_name: balance-1
    image: openjdk:17-oracle
    volumes:
      - ./balance/build/libs/balance-0.0.1-SNAPSHOT.jar:/balance.jar
    command: [ "java", "-jar", "balance.jar" ]
    environment:
      USER_PROFILE_HOST: "balancer/user-profile"
      BILLING_HOST: "billing"
      BALANCE_HOST: "balancer/balance"
    networks:
      - skufbet

  balance-2:
    container_name: balance-2
    image: openjdk:17-oracle
    volumes:
      - ./balance/build/libs/balance-0.0.1-SNAPSHOT.jar:/balance.jar
    command: [ "java", "-jar", "balance.jar" ]
    environment:
      USER_PROFILE_HOST: "balancer/user-profile"
      BILLING_HOST: "billing"
      BALANCE_HOST: "balancer/balance"
    networks:
      - skufbet

  billing:
    container_name: billing
    image: openjdk:17-oracle
    volumes:
      - ./billing-mock/build/libs/billing-mock-0.0.1-SNAPSHOT.jar:/billing-mock.jar
    command: [ "java", "-jar", "billing-mock.jar" ]
    networks:
      - skufbet

  keycloak-postgres:
    image: library/postgres:${KC_POSTGRES_IMAGE_TAG:-14}
    container_name: ${POSTGRES_CONTAINER_NAME:-postgres}
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: pg_isready -d postgres
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - ${KC_POSTGRES_PORT_MAPPING:-5435}:5432
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - skufbet

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    container_name: keycloak
    command:
      - start --auto-build --db postgres --hostname-strict-https false --hostname-strict false --proxy edge --http-enabled true --import-realm --spi-user-profile-legacy-user-profile-read-only-attributes *_RES_ACCESS_MODE
    environment:
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_DB_SCHEMA: public
      KC_FEATURES: preview
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - type: bind
        source: ./core-api/src/main/resources/keycloak/import/realm-export.json
        target: /opt/keycloak/data/import/realm-export.json
        read_only: true
    ports:
      - "8282:8080"
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080/realms/master"]
      start_period: 10s
      interval: 30s
      retries: 3
      timeout: 5s
    networks:
      - skufbet

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - skufbet

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - skufbet

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8082:8080"
    depends_on:
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - skufbet

networks:
  skufbet:
    driver: bridge
