rootProject.name = "skufbet"
include("core-api")
include("database-skufdb")
include("user-profile")
include("balance")
include("database-balance")
include("utils-database")
include("billing-mock")
include("database-userprofile")
include("common-user-profile")
